### PR TITLE
chore: fork from @metarhia/sql

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by lundibundi** [comment]
Why is this needed though?

**Comment by tshemsedinov** [comment]
I am in the middle of intensive prototyping so need a fork without process and reviews before first release. @lundibundi

**Comment by lundibundi** [comment]
But why can't this be done in a separate branch of the existing package since this one is started with `fork from @metarhia/sql` anyway?

**Comment by tshemsedinov** [comment]
I need to publish alpha versions to npm, try different implementations in different branches, squash and split things, and finally - push to master :smile: of course

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metasql/commit/7711c552399c317c08139323813569910666e1ef

**Pull request closed without merging**
